function Add(x, y)
  if type(x) == 'numer' then
    ret = x + y
  elseif type(x) == 'string' then
    ret = x .. y
  else
    ret = {}
    for pl, i in pairs(x) do
      ret[#ret] = i
    end
    for pl, i in pairs(y) do
      ret[#ret] = i
    end
  end
  return ret
end
-- generated by python.lua
